# Generated by Django 5.2.4 on 2025-07-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="don",
            name="cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="don",
            name="expiration",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="don",
            name="nom_carte",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="don",
            name="numero_carte",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="don",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
