# Generated by Django 5.2.4 on 2025-07-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0002_don_cvv_don_expiration_don_nom_carte_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Don",
        ),
    ]
