# Generated by Django 5.2.4 on 2025-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Galerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "type_media",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Vidéo")], max_length=10
                    ),
                ),
                ("chemin_fichier", models.CharField(max_length=255)),
                ("evenement", models.CharField(max_length=255)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
