# Generated by Django 5.2.4 on 2025-07-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galerie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_media",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Vidéo")], max_length=10
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="galerie/")),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("membre", "Membre"),
                            ("blog", "Blog"),
                            ("galerie", "Galerie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Galerie",
        ),
    ]
