# Generated by Django 5.2.4 on 2025-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galerie", "0002_image_delete_galerie"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="afficher_dans_carousel",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="origine",
            field=models.CharField(
                choices=[
                    ("profil", "Photo de profil"),
                    ("userpost", "Post utilisateur"),
                    ("blog", "Blog"),
                    ("galerie", "Galerie"),
                ],
                max_length=20,
            ),
        ),
    ]
