# Generated by Django 5.2.4 on 2025-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=100)),
                ("photo", models.CharField(max_length=100)),
                ("ville", models.CharField(max_length=50)),
                ("profession", models.CharField(max_length=50)),
                ("statut", models.CharField(max_length=50)),
                ("mini_cv", models.TextField()),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("is_actif", models.BooleanField(default=True)),
            ],
        ),
    ]
