# Generated by Django 5.2.4 on 2025-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="confirmation_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="membre",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
