# Generated by Django 5.2.4 on 2025-07-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="username",
            field=models.CharField(default="user_default", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
