# Generated by Django 5.2.4 on 2025-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("fichier", models.FileField(upload_to="ressources/")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("memoire", "Mémoire"),
                            ("cv", "Modèle de CV"),
                            ("cours", "Cours"),
                            ("guide", "Guide"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="publication",
            name="fichier_joint",
            field=models.FileField(blank=True, null=True, upload_to="publications/"),
        ),
    ]
