# Generated by Django 5.2.4 on 2025-07-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0002_ressource_alter_publication_fichier_joint"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="valide",
            field=models.BooleanField(
                default=False,
                help_text="La publication doit être validée par un administrateur pour être affichée.",
            ),
        ),
    ]
