# Generated by Django 5.2.4 on 2025-07-18 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_publication_valide"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagePublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_titre", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("lu", models.BooleanField(default=False)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_publication",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
