# Generated by Django 5.2.4 on 2025-07-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_messagepublication"),
    ]

    operations = [
        migrations.AddField(
            model_name="membres",
            name="is_promoteur",
            field=models.BooleanField(
                default=False, help_text="Ce membre est un promoteur de l'association."
            ),
        ),
    ]
