# Generated by Django 5.2.4 on 2025-07-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_membres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membres",
            old_name="is_actif",
            new_name="is_active",
        ),
    ]
