# Generated by Django 5.2.4 on 2025-07-21 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom complet")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "sujet",
                    models.CharField(blank=True, max_length=200, verbose_name="Sujet"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("lu", "Lu"),
                            ("repondu", "Répondu"),
                            ("archivé", "Archivé"),
                        ],
                        default="nouveau",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_lecture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "reponse",
                    models.TextField(blank=True, verbose_name="Réponse administrateur"),
                ),
                (
                    "date_reponse",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réponse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-date_creation"],
            },
        ),
    ]
