# Generated by Django 5.2.4 on 2025-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                ("image", models.CharField(blank=True, max_length=255)),
                ("fichier_joint", models.CharField(blank=True, max_length=255)),
                ("categorie", models.CharField(max_length=100)),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
