# Generated by Django 5.2.4 on 2025-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adhesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_adherent", models.CharField(max_length=20)),
                (
                    "type_adhesion",
                    models.CharField(
                        choices=[
                            ("etudiant", "Etudiant"),
                            ("freelance", "Freelance"),
                            ("entrepreneur", "Entrepreneur"),
                            ("autres", "Autres"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=5, max_digits=10)),
                ("moyen_paiment", models.CharField(max_length=50)),
                ("numero_transaction", models.CharField(max_length=100)),
            ],
        ),
    ]
