# Generated by Django 5.2.4 on 2025-07-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Don",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("orange_money", "Orange Money"),
                            ("mtn_money", "MTN Mobile Money"),
                            ("carte", "Carte bancaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("statut", models.CharField(default="en_attente", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("nom_carte", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_carte",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("expiration", models.CharField(blank=True, max_length=7, null=True)),
                ("cvv", models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
